name: Build & Push Docker Image

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for faster builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub securely
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and Tag Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/messaging_app:latest \
            -f messaging_app/Dockerfile \
            messaging_app

      # 5. Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/messaging_app:latest

      # 6. Confirm Deployment
      - name: Verify Image on Docker Hub
        run: echo "Docker image pushed successfully 🚀"
